
import os
import subprocess
import sys
import json
import time


# Configuration
# Try to find the correct python from the user's environment
CANDIDATE_PYTHON = r'D:\Anaconda3\envs\timellm\python.exe'
if os.path.exists(CANDIDATE_PYTHON):
    PYTHON_EXEC = CANDIDATE_PYTHON
else:
    PYTHON_EXEC = sys.executable

print(f"Using Python: {PYTHON_EXEC}")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
SPLIT_SCRIPT = os.path.join(SCRIPT_DIR, 'split_data_by_cluster.py')
MAIN_SCRIPT = os.path.join(PROJECT_ROOT, 'run_main.py')
CLUSTER_FILE = os.path.join(PROJECT_ROOT, 'station_to_cluster.json')
DATASET_DIR = os.path.join(PROJECT_ROOT, 'dataset', 'EV_Data')

# Default Arguments for Time-LLM (Can be overridden)
BASE_ARGS = [
    '--task_name', 'long_term_forecast',
    '--is_training', '1',
    '--root_path', './dataset/EV_Data',
    '--model_id', 'EV_Cluster',
    '--model', 'TimeLLM',
    '--data', 'EV_Data',
    '--features', 'M', # Changed from MS to M (Multivariable-to-Multivariable)
    '--seq_len', '96', # Matched to batch file
    '--label_len', '24', # Matched to batch file
    '--pred_len', '24', # Matched to batch file
    '--enc_in', '7',  # Will be updated per cluster
    '--dec_in', '7',  # Will be updated per cluster
    '--c_out', '7',   # Will be updated per cluster
    '--cov_dim', '7', # <-- New parameter enabling Late Fusion of covariates!
    '--des', 'Exp',
    '--d_model', '64', # Increased from 32 to 64 for better capacity (Plan C)
    '--d_ff', '256',   # Increased from 128 to 256
    '--batch_size', '1', # Decreased to 1 to avoid OOM
    '--learning_rate', '0.0001', # Reduced from 0.0005 to 0.0001 for finer convergence
    '--llm_layers', '24', # Maintained at 24 (防止 CUDA Out of Memory)
    '--train_epochs', '3', # Maintained at 3
    '--patience', '3',     # Maintained at 3
    '--llm_model', '/mnt/workspace/local_models/Qwen3.5-9B', 
    '--llm_dim', '4096',
    '--itr', '1',
    '--model_comment', 'Cluster_Training_Run' # Added required argument
]

def run_command(command, cwd=PROJECT_ROOT):
    print(f"Running: {' '.join(command)}")
    try:
        # result = subprocess.run(command, cwd=cwd, check=True) # Don't capture output, let it flow to stdout
        # Use Popen to stream output if needed, but run() is fine for blocking
        subprocess.run(command, cwd=cwd, check=True)# shell=True sometimes needed on Windows for path resolution
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e}")
        sys.exit(1)

def main():
    print("=== Step 1: Split Data by Cluster ===")
    split_cmd = [PYTHON_EXEC, SPLIT_SCRIPT, '--cluster_path', CLUSTER_FILE]
    run_command(split_cmd)
    
    # Check for the config file generated by the split script
    config_path = os.path.join(PROJECT_ROOT, 'cluster_run_config.json')
    if not os.path.exists(config_path):
        print(f"Error: {config_path} not found. Did split_data_by_cluster.py run correctly?")
        sys.exit(1)
        
    with open(config_path, 'r') as f:
        cluster_configs = json.load(f)
        
    print(f"\n=== Step 2: Run Training for {len(cluster_configs)} Clusters ===")
    
    for config in cluster_configs:
        cluster_id = config['cluster_id']
        data_file = config['file']
        enc_in = str(config['enc_in'])
        stations_count = config['stations_count']
        
        print(f"\n---------------------------------------------------------")
        print(f"Starting Training for Cluster {cluster_id}")
        print(f"Data File: {data_file}")
        print(f"Stations: {stations_count} (Total Input Vars: {enc_in})")
        print(f"---------------------------------------------------------")
        
        # Construct Command
        cmd = [PYTHON_EXEC, MAIN_SCRIPT] + BASE_ARGS.copy()
        
        # Update Arguments
        # Update data_path
        cmd.append('--data_path')
        cmd.append(data_file)
        
        # Update dimensions
        for arg in ['--enc_in', '--dec_in', '--c_out']:
            if arg in cmd:
                idx = cmd.index(arg)
                cmd[idx+1] = enc_in
            else:
                cmd.extend([arg, enc_in])
                
        # Update Model ID to be unique
        if '--model_id' in cmd:
            idx = cmd.index('--model_id')
            cmd[idx+1] = f"EV_Cluster_{cluster_id}"

        # Enable Automatic Mixed Precision (AMP) to prevent CUDA errors / OOM
        # cmd.append('--use_amp')  <-- Disabled because it caused NaNs
            
        # Run
        try:
            run_command(cmd)
            print(f"Cluster {cluster_id} Training Completed.\n")
        except SystemExit:
            print(f"Cluster {cluster_id} Training Failed.")
            # Optional: Decide whether to continue or stop. 
            # For now, we let it flow to the pause so user can see the error.

        print("="*60)
        print(f"Cluster {cluster_id} 处理完毕。")
        print(">>> 请检查上方日志是否有报错。")
        print(">>> 按 [回车键] 继续下一个 Cluster 的训练 (或按 Ctrl+C 终止)...")
        print("="*60)
        input() # Wait for user confirmation

    print("=== All Clusters Processed Successfully ===")

if __name__ == "__main__":
    main()
